#!/bin/bash
option=$(echo -e "\nUS-Intrnc\nBR-ABNT-2" | dmenu -i -p "Choose your keyboard")

case $option in 
	US-Intrnc) echo setxkbmap -model pc104 -layout us_intl > ~/.config/keyboardConfig.sh;;
	BR-ABNT-2) echo setxkbmap -layout br -model abnt2 -variant abnt2 > ~/.config/keyboardConfig.sh;;
esac

chmod +x ~/.config/keyboardConfig.sh
~/.config/keyboardConfig.sh
