#!/bin/bash
option=$(echo -e "English\nPortuguese" | dmenu -i -p "Translate clipboard to:" -nb blue)

case $option in 
	English) lang=en;;
	Portuguese) lang=pt;;
esac

result="$(wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=$(echo $lang)&dt=t&q=$(xsel -o | sed "s/[\"'<>]//g")" | jq 'foreach .[0] as $item (null;null;$item[][0])' | sed 's/\"$//g' | sed 's/^\"//g' | sed 's/[\\n]*$//g')"

notify-send --icon=info "$(echo $result)"

echo $result | xclip -se c
