#!/bin/bash

# Tells sudo to use a custom password prompter
# sudo uses it when the -A flag are used
export SUDO_ASKPASS=$(realpath ~/.config/i3/scripts/doAskPassword)

# Show the options at dmenu
option=$(echo -e "Cancel\nReceive file\nStop all" | dmenu -i -p "Bluetooth:")

case $option in
	"Receive file") 
		# turns on the bluetooth devices
		sudo -A rfkill unblock bluetooth

		# Starts the bluetooth daemon
		sudo -A bluetoothd -C &

		# Waits until the process is up
		until pids=$(pidof bluetoothd)
		do
			echo starting...
			sleep 1
		done
		
		# Starts receiving files
		sudo -A obexpushd -B -o /tmp 
		;;
	"Stop all")
		# Kill all daemons
		sudo -A kill -9 $(pidof bluetoothd)
		sudo -A kill -9 $(pidof obexpushd)
		# Turn off bluetooth devices
		sudo -A rfkill block bluetooth
		;;
esac
