#!/bin/bash
option=$(echo -e "Nothing\nSleep\nPoweroff\nReboot" | dmenu -i -p "Choose your destiny!!" -nb red)

case $option in 
	Poweroff) poweroff;;
	Reboot) reboot;;
	Sleep) systemctl suspend;;
esac
