#!/bin/bash
ip=$(ip address show wlx503eaab65e33 | grep inet | grep wlx503eaab65e33 | awk '{ print $2 }')
activeNetwork=$(iwconfig wlx503eaab65e33 | grep ESSID | sed 's/.*ESSID://' | sed 's/"//g')
if [ "$ip" == "" ]
then
	echo  No wifi
	echo
	echo "#ff0000"
else
	echo  $activeNetwork - $ip
	echo
	echo "#00ff00"
fi
