#!/bin/bash
date +%T\ %Y-%m-%d

function notify {
	notify-send --icon=stock_calendar -t 0 "$(ncal -b | cat -A | sed -E 's/\_\^H(.)/<span color="#000000" font="14px"><b>\1<\/b><\/span>/g' | sed 's/M-CM-!/á/g' | sed 's/\$//g')"

}

# For i3
case $BLOCK_BUTTON in
	1) notify;;
esac

# For command line
case $1 in
	1) notify;;
esac

