#!/bin/bash

function notify {
	calendar=$(ncal -b | cat -A | sed -E 's/\_\^H(.)/<span color="#000000" font="14px"><b>\1<\/b><\/span>/g' | sed 's/M-CM-!/á/g' | sed 's/\$//g')

	appointments=$(calcurse -d 3 --format-apt=' - %m (%S → %E)\n' --format-recur-apt=' - %m (%S → %E)\n' | sed 's/*/-/'| sed -E 's/(..\/..\/..:)/<span color="#000055" font="14px"><b>\1<\/b><\/span>/')

	todos=$(calcurse -t --format-todo '(%p) %m\n' | sed -E 's/(.*:)/<span color="#000055" font="14px"><b>\1<\/b><\/span>/')

	notify-send --icon=stock_calendar -t 0 "$calendar
$todos

$appointments"
}

# For i3
case $BLOCK_BUTTON in
	1) notify;;
	*) date +%T\ %Y-%m-%d;;
esac

# For command line
case $1 in
	1) notify;;
	*) date +%T\ %Y-%m-%d;;
esac

