#!/bin/bash
mute=$(pactl list sinks | grep Mudo | awk '{print $2}')

baseVolume=$(pactl list sinks | grep Volume | grep base | cut -d':' -f2 | cut -d'/' -f1)
lefvol=$(pactl list sinks | grep Volume | head -n 1 | cut -d':' -f 3 | cut -d' ' -f 2)
rigvol=$(pactl list sinks | grep Volume | head -n 1 | cut -d':' -f 4 | cut -d' ' -f 2)

lefperc=$(echo "scale=2; $lefvol / $baseVolume" | bc)
rigperc=$(echo "scale=2; $rigvol / $baseVolume" | bc)

if [ "$mute" == "sim" ] || [ "$mute" == "yes" ]
then
	echo  Mute\($lefperc/$rigperc\)
	echo
	echo "#000000"
else
	echo $lefperc/$rigperc
	echo
	if (( $(echo "$lefperc > 1" | bc) ))
	then
		echo "#ff0000"
	else
		echo "#00ff00"
	fi
fi
