#!/bin/bash
ip=$(ip address show wlp2s0 | grep inet | grep wlp2s0 | awk '{ print $2 }')
activeNetwork=$(iwconfig wlp2s0 | grep ESSID | sed 's/.*ESSID://' | sed 's/"//g')
if [ "$ip" == "" ]
then
	echo  No wifi
	echo
	echo "#ff0000"
else
	echo  $activeNetwork - $ip
	echo
	echo "#00ff00"
fi
